### ISSUE TITLE
OGP対応

### ISSUE THREAD

**Issue by tarakish** [tarakish/burn-down-chart-for-reading-sessions#6]
## やりたいこと
わざわざURLを押さなくてもOGPで見れると最高。
チャートが無理であれば、シンプルにベロシティだけでもよい。

## Task
- [x] できるかどうか調査

**Comment by da-yoshi-k** [comment]
## 🙅試してみたけどダメそうだった例
- [QuickChart](https://quickchart.io/)というサービス
特定のURLの後ろに描画したいデータを渡す（Chart.jsと同じフォーマットを使いまわせそう）だけで画像を作成できるので、metaタグに入れ込めればと思ったのですが、今のフロントのJSオンリーだと動的に生成するのが難しそうです。

例えば、前回までのデータを流用すると以下のようなURLで図形の作成が可能です。
[https://quickchart.io/chart?version=3&c=%7B%0A%20%20type%長いので文面上は省略](https://quickchart.io/chart?version=3&c=%7B%0A%20%20type%3A%20%22line%22%2C%0A%20%20data%3A%20%7B%0A%20%20%20%20labels%3A%20%5B%0A%20%20%220%22%2C%0A%20%20%2211%2F21%22%2C%0A%20%20%2211%2F28%22%2C%0A%20%20%2212%2F5%22%2C%0A%20%20%2212%2F19%22%2C%0A%20%20%2212%2F26%22%2C%0A%20%20%222024%2F1%2F9%22%2C%0A%20%20%221%2F16%22%2C%0A%20%20%221%2F23%22%2C%0A%20%20%221%2F30%22%2C%0A%20%20%222%2F6%22%2C%0A%20%20%222%2F13%22%2C%0A%5D%2C%0A%20%20%20%20datasets%3A%20%5B%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20label%3A%20%22Read%20Points%22%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B146%2C%20137%2C%20119%2C%2097%2C%2082%2C%2071%5D%2C%0A%20%20%20%20%20%20%20%20borderColor%3A%20%22%23ff6347%22%2C%0A%20%20%20%20%20%20%20%20backgroundColor%3A%20%22%23ff6347%22%2C%0A%20%20%20%20%20%20%20%20customTextEnabled%3A%20true%2C%0A%20%20%20%20%20%20%20%20fill%3A%20false%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20label%3A%20%22Trend%20Line%22%2C%0A%20%20%20%20%20%20%20%20data%3A%20%5B146%2C%20131%2C%20116%2C%20101%2C%2086%2C%2071%2C%2056%2C%2041%2C%2026%2C%2011%2C%20-4%2C%20-19%5D%2C%0A%20%20%20%20%20%20%20%20borderColor%3A%20%22%2300FFFF%22%2C%0A%20%20%20%20%20%20%20%20backgroundColor%3A%20%22%2300FFFF%22%2C%0A%20%20%20%20%20%20%20%20fill%3A%20false%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%20%20%7D%2C%0A%20%20options%3A%20%7B%0A%20%20%20%20scales%3A%20%7B%0A%20%20%20%20%20%20y%3A%20%7B%0A%20%20%20%20%20%20%20%20beginAtZero%3A%20true%2C%0A%20%20%20%20%20%20%20%20min%3A%200%2C%0A%20%20%20%20%20%20%20%20title%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20display%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20text%3A%20%22Number%20of%20Pages%22%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%20%20%7D%2C%0A%7D)

**Comment by da-yoshi-k** [comment]
## 力技で行くなら
- canvas要素の近くに「グラフをダウンロードする」ボタンを追加。(`.toDataURL`で[画像を表現したものが入ったデータ URL](https://developer.mozilla.org/ja/docs/Web/API/HTMLCanvasElement/toDataURL)にできるようです)
- データの追加と合わせて画像ダウンロード→所定の位置の画像を更新する。
- metaタグには固定の画像URLを設定しておく。

試しにやってみたコミット https://github.com/da-yoshi-k/burn-down-chart-for-reading-sessions/commit/20b45e87053055606d5de5893b5a5f632b5faf1b
※自分のGitHub Pagesにデプロイする前提で作ったので、本番向けにはda-yoshi-k→tarakishにドメインを変更する必要があります。

## サンプル
以下をデプロイしているので、SlackやDiscordなどにURLを貼り付けてみていただけると使用感がわかると思います。
https://da-yoshi-k.github.io/burn-down-chart-for-reading-sessions/clean_agile/

「グラフをダウンロード」ボタンが足されたイメージ（無骨ですが）
![image](https://github.com/tarakish/burn-down-chart-for-reading-sessions/assets/54100082/d51fbc7f-8556-4954-8864-88cc81993034)

**Comment by da-yoshi-k** [comment]
### 確認点への回答
> 力技の方だとchart.jsで描画されたものをそのまま使える認識であってますでしょうか？

→特定のcanvas要素を画像化するので、chart.jsで描画されたものをそのまま利用できます。

> 更新方法としてはローカルでACHIEVEMENT_DATAを更新　→　ローカルで画像保存　→　ローカルで画像差し替え　→　mainにpush、のように更新するイメージですか？

→手動で恐縮ですが、上記の手順であっています。

### 感じたことへの回答(口頭でも会話したもの)
バーンダウンダウンチャートの価値は、作業の進捗を視覚的にわかるようにすることであり、ベロシティの数字自体は最重要ではないと思っています。
（今回の例では、本が変わると相対サイズを合わせたりしないとベロシティの数字は容易に変わる）

実際の開発だと、以下のようなシチュエーションは想定されます。 ※アジャイルサムライ8章を参照
- ストーリーが追加されて、これまでのベロシティの数字も含めて見積り直したい。
- 今回のポイント数は参加者の平均値のようになっているが、本来はメンバーの消化した作業量の総計。
  チームメンバーの増減したタイミングでベロシティの変化をすぐに知りたいというニーズは考えられる。

ただ、基本的にベロシティの数字のみに固執するのは健全ではないかなと個人的には思います。
